Vagrant.configure("2") do |config|
  config.vm.box = "windows10"
  config.vm.define "windows10-dev"
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.guest = :windows
  config.windows.halt_timeout = 15
  config.vm.network "forwarded_port", guest: 3389, host: 3392, id: "rdp", auto_correct: true
  config.vm.synced_folder "d:/", "/data"
  config.vm.provision "shell" do |s|
    s.inline = "c:/vagrant/install-dev.cmd"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = "8192"
    vb.cpus = 2
	  vb.name = "windows10-dev"
	  vb.customize ["modifyvm", :id, "--vram", "128"]
	  vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
	  vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
  end
end
